/**
 * Google Apps Script (Code.gs) for MediNexus AI Free Email Webhook API
 * Deploy as Web App -> Execute as: "Me" -> Who has access: "Anyone"
 */

function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);
    var recipient = data.recipientEmail || "patient.sukhee@gmail.com";
    var subject = data.subject || "MediNexus AI Health Notification";
    var stageName = data.stageName || "Appointment Stage Notification";
    var patientName = data.patientName || "Sukhee";
    var details = data.details || "Your healthcare notification details.";

    var htmlBody = "" +
      "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff;'>" +
        "<div style='border-bottom: 2px solid #0284c7; padding-bottom: 12px; margin-bottom: 16px;'>" +
          "<h2 style='color: #0284c7; margin: 0; font-size: 22px;'>🏥 MediNexus AI Healthcare</h2>" +
          "<span style='color: #64748b; font-size: 12px;'>Multi-Stage Patient Notification System</span>" +
        "</div>" +

        "<h3 style='color: #0369a1; background: #e0f2fe; padding: 10px 14px; border-radius: 8px; margin-top: 0;'>" + stageName + "</h3>" +

        "<p style='color: #334155; font-size: 14px;'>Dear <strong>" + patientName + "</strong>,</p>" +

        "<p style='color: #475569; font-size: 14px; line-height: 1.6;'>" + details + "</p>" +

        "<div style='background-color: #f8fafc; border: 1px solid #cbd5e1; padding: 16px; border-radius: 12px; font-size: 13px; margin: 20px 0; color: #334155;'>" +
          "<strong style='color: #0284c7; font-size: 14px;'>Appointment & Patient Summary:</strong><br><br>" +
          "• <strong>Health ID:</strong> MNX-10291<br>" +
          "• <strong>Attending Doctor:</strong> Dr. Arjun Mehta (Cardiology)<br>" +
          "• <strong>Location:</strong> Room 204, Cardiology Department<br>" +
          "• <strong>Queue Position:</strong> #4 in Queue (~12 Mins Wait)<br>" +
          "• <strong>Mobile Number:</strong> +91 9865881000" +
        "</div>" +

        "<p style='font-size: 12px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 12px; margin-top: 24px;'>" +
          "This email was automatically generated by MediNexus AI Platform using Google Apps Script Webhook API." +
        "</p>" +
      "</div>";

    MailApp.sendEmail({
      to: recipient,
      subject: subject,
      htmlBody: htmlBody
    });

    return ContentService.createTextOutput(JSON.stringify({ status: "SUCCESS", message: "Email sent successfully to " + recipient }))
      .setMimeType(ContentService.MimeType.JSON);
  } catch (err) {
    return ContentService.createTextOutput(JSON.stringify({ status: "ERROR", error: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}
