import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, FileSpreadsheet, FileText, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Tables } from "@/integrations/supabase/types";

type Patient = Tables<"patients">;

interface ExportMenuProps {
  patients: Patient[];
}

const ExportMenu = ({ patients }: ExportMenuProps) => {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPDF = () => {
    if (patients.length === 0) {
      toast.error("No patients to export");
      return;
    }

    // Create printable HTML content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Patient Report - MediLedger AI</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; }
          h1 { color: #1a1a2e; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
          .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }
          .powered-by { font-size: 12px; color: #666; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #6366f1; color: white; }
          tr:nth-child(even) { background-color: #f9fafb; }
          .footer { margin-top: 30px; font-size: 12px; color: #666; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Patient Report</h1>
          <div class="powered-by">Generated by MediLedger AI</div>
        </div>
        <p>Total Patients: ${patients.length}</p>
        <p>Generated: ${new Date().toLocaleDateString()}</p>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Date of Birth</th>
              <th>Gender</th>
              <th>Blood Type</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Conditions</th>
            </tr>
          </thead>
          <tbody>
            ${patients.map(p => `
              <tr>
                <td>${p.full_name}</td>
                <td>${p.date_of_birth}</td>
                <td>${p.gender || '-'}</td>
                <td>${p.blood_type || '-'}</td>
                <td>${p.email || '-'}</td>
                <td>${p.phone || '-'}</td>
                <td>${p.chronic_conditions?.join(', ') || '-'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">
          <p>This report was generated by MediLedger AI - Secure Healthcare Data Management</p>
        </div>
      </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      printWindow.print();
    }
    toast.success("PDF export ready for printing");
  };

  const exportToCSV = async () => {
    if (patients.length === 0) {
      toast.error("No patients to export");
      return;
    }

    setIsExporting(true);
    try {
      const { data, error } = await supabase.functions.invoke("export-to-sheets", {
        body: { patients },
      });

      if (error) throw error;

      if (data.csvContent) {
        const blob = new Blob([data.csvContent], { type: "text/csv" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `patients-${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success("CSV downloaded successfully");
      }
    } catch (error) {
      console.error("Export error:", error);
      toast.error("Failed to export data");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" disabled={isExporting}>
          {isExporting ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Download className="mr-2 h-4 w-4" />
          )}
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportToPDF}>
          <FileText className="mr-2 h-4 w-4" />
          Export as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportToCSV}>
          <FileSpreadsheet className="mr-2 h-4 w-4" />
          Export as CSV/Sheets
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ExportMenu;
